### ISSUE TITLE
On a real Android device, the audio plays only once.

### ISSUE THREAD

**Issue by rajaarav0** [mearaj/solution_76450197#1] opened 2023-06-23 05:39 UTC
Hello Brother, I would like to raise an issue regarding the onCountdownChange() function in my app. It seems to be working perfectly fine on the iOS simulator. However, when testing it on a Redmi Note 7 Pro device, I encountered an unexpected behavior.

Specifically, the audio playback within the function only occurs once on the Redmi Note 7, whereas it should ideally play 5 times as intended. Interestingly, the vibration, which was added later on, works correctly and triggers 5 times.

I would appreciate any insights or assistance in resolving this issue. Thank you for your attention to this matter.

Device Info:
- Redmi Note 7 Pro
- Android Version 10

Thank you.

**Comment by mearaj** [comment] 2023-06-23 06:01
Hi @rajaarav0 , thanks for filing this issue, I will look into it and will get back to you. :)

**Comment by mearaj** [comment] 2023-06-23 14:47
HI @rajaarav0 , I am unable to reproduce it. Also I found that on some devices I have manually increase the volume. I don't have Redmi Note 7 Pro, but please if you can reproduce this issue on any android emulator, I would be very grateful.

**Comment by rajaarav0** [comment] 2023-06-25 10:07
Hello Mearaj Bhai, For some reason android emulator is not working on my laptop. It's fine thank you so much. @mearaj

**Comment by mearaj** [comment] 2023-06-26 09:17
@rajaarav0 I am closing this , anytime stuck anywhere, please do let me know. Not only for this code, for anything else as well. Thanks :)

**Closed by mearaj** 2023-06-26 09:17 UTC

**Comment by rajaarav0** [comment] 2023-06-26 09:45
Mearaj Bhai Instagram pe add Karlo. Even I'm from Mumbai. Have sent you a request from the username Rajaarav. Thank you brother.

**Comment by mearaj** [comment] 2023-06-26 09:53
> Mearaj Bhai Instagram pe add Karlo. Even I'm from Mumbai. Have sent you a request from the username Rajaarav. Thank you brother.

Yes, request sent. Thanks a lot :)
